### PR TITLE
Fix warnings with SDK release candidate.

### PR DESCRIPTION
**Pull request by mhdostal**

### CODE REVIEW

**Review by zkline101 — COMMENTED** [review]
I see four other warnings in the examples app. Two are SwiftLint warnings and the other two are Xcode warnings. Can you fix those as well?

**Comment by mhdostal** [comment]
Hmmm, I don't see any other warnings.  I'm using Xcode 13.2.1.  But let me update SwiftLint.

**Comment by zkline101** [comment]
>  I'm using Xcode 13.2.1

Ah, I see I am using Xcode 13.3. I can fix those two Xcode warnings if you would like.

**Review by zkline101 — APPROVED** [review]

**Review by dfeinzimer — APPROVED** [review]
Looks good!

**Comment by mhdostal** [comment]
Excellent, thanks!

**Pull request merged**
