### PR TITLE
Fix Auto Layout issues with MeasureToolbar

### PR DESCRIPTION
**Pull request by philium**
The issues stemmed from the toolbar laying out its subviews before it had a valid size. The solution I used is to assign the toolbar's items in `layoutSubviews()`, which is only called after the toolbar is positioned in its super view. I also made the result view a bar item.

### CODE REVIEW

**Comment by rolson** [comment]
I was just testing this. If I use the area mode:

image


and then tap the "acres" button, I still see linear units:

image

I don't see that in `master`

**Comment by rolson** [comment]
to reproduce the bug:
- go to the measure feature mode:
image

- tap a line feature:

image

- go into measure area mode:

image

- tap the acres button

**Comment by rolson** [comment]
Actually - just re-tested with master now that I know the exact steps and I see the issue in master as well. So I will approve this PR and create a separate issue for this bug.

**Comment by philium** [comment]
@rolson Thank you for looking at this so carefully and finding that bug!

**Pull request merged**
